### ISSUE TITLE
Use template in README

### ISSUE THREAD

**Issue by ghost** [watilde/fly-less#1]
Until we come up with a more efficient way to generate Fly plugin projects (maybe using `yo`, or adding it to the CLI engine like `fly --new plugin_path`), check out [this basic template](https://gist.github.com/bucaran/f018ade8dee8ae189407).

Thanks! :+1:

**Comment by watilde** [comment]
Thanks for your comment! I'll do it, but here is the current status: https://twitter.com/watilde/status/616550204938977280

After getting the namespace, I'll write up.

**Comment by watilde** [comment]
Closing as resolved!

**Comment by ghost** [comment]
:+1:
